name: .NET Core Desktop
on:
  push:
    tags:
      - "*.*.*.*"
jobs:
  build:
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup-MS Build
      uses: microsoft/setup-msbuild@v1.3
    
    # Pull and Restore Nuget
    - name: Setup Nuget
      uses: Nuget/setup-nuget@v2.0.0
      
    - name: Nuget Restore
      run: nuget restore ./NanoTwitchLeafs.sln
      
    # Build Project
    - name: Build
      run: msbuild.exe ./NanoTwitchLeafs.sln /p:platform="Any CPU" /p:configuration="Release"
    # Upload Artifact
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        # Artifact name
        name: NanoTwitchLeafs #.zip will be added automatically
        path: ./bin/release/  
  create-release:
    permissions: write-all
    needs: build
    runs-on: ubuntu-latest
    steps:
    # Download Artifact
    - name: Download Artifact
      uses: actions/download-artifact@v4.2.1
      with:
          name: NanoTwitchLeafs
    # Create ServiceCredentials
    - name: Create ServiceCredentials file
      uses: jsdaniell/create-json@v1.2.3
      with:
        name: "ServiceCredentials"
        dir: '.'
        json: >
          { 
            "TwitchApiCredentials": {
              "ClientId": "${{ secrets.TWITCHCLIENTID }}",
              "ClientSecret": "${{ secrets.TWITCHSECRET }}"
            },
            "StreamLabsApiCedentials": {
              "ClientId": "${{ secrets.STREAMLABSCLIENTID }}",
              "ClientSecret": "${{ secrets.STREAMLABSSECRET }}"
            },
            "HyperateApi": {
              "ApiKey": "${{ secrets.HYPERATE_API_KEY }}"
            }
          }  
    - name: Check Directory
      run: |
        ls -l
    # Zip Files
    - name: Build ZIP
      run: |
        zip -r ../NanoTwitchLeafs-${{ github.ref_name }}.zip .
        cd ../
        ls -l
    # Create Release
    - name: Create Release and Upload asset
      uses: softprops/action-gh-release@v2
      with:
        fail_on_unmatched_files: true
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        files: NanoTwitchLeafs-${{ github.ref_name }}.zip
        token: ${{ github.token }}
        make_latest: true
